// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0
// source: swarm.proto

package swarm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WTester_ActorRegister_FullMethodName  = "/WTester/ActorRegister"
	WTester_ActorStage_FullMethodName     = "/WTester/ActorStage"
	WTester_DirectorStage_FullMethodName  = "/WTester/DirectorStage"
	WTester_ActorTerminate_FullMethodName = "/WTester/ActorTerminate"
)

// WTesterClient is the client API for WTester service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WTesterClient interface {
	// 子节点注册/下线/结束
	ActorRegister(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	ActorStage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	DirectorStage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	ActorTerminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type wTesterClient struct {
	cc grpc.ClientConnInterface
}

func NewWTesterClient(cc grpc.ClientConnInterface) WTesterClient {
	return &wTesterClient{cc}
}

func (c *wTesterClient) ActorRegister(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, WTester_ActorRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wTesterClient) ActorStage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, WTester_ActorStage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wTesterClient) DirectorStage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, WTester_DirectorStage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wTesterClient) ActorTerminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, WTester_ActorTerminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WTesterServer is the server API for WTester service.
// All implementations must embed UnimplementedWTesterServer
// for forward compatibility.
type WTesterServer interface {
	// 子节点注册/下线/结束
	ActorRegister(context.Context, *RegisterRequest) (*CommonResponse, error)
	ActorStage(context.Context, *StageRequest) (*CommonResponse, error)
	DirectorStage(context.Context, *StageRequest) (*CommonResponse, error)
	ActorTerminate(context.Context, *TerminateRequest) (*CommonResponse, error)
	mustEmbedUnimplementedWTesterServer()
}

// UnimplementedWTesterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWTesterServer struct{}

func (UnimplementedWTesterServer) ActorRegister(context.Context, *RegisterRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActorRegister not implemented")
}
func (UnimplementedWTesterServer) ActorStage(context.Context, *StageRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActorStage not implemented")
}
func (UnimplementedWTesterServer) DirectorStage(context.Context, *StageRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DirectorStage not implemented")
}
func (UnimplementedWTesterServer) ActorTerminate(context.Context, *TerminateRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActorTerminate not implemented")
}
func (UnimplementedWTesterServer) mustEmbedUnimplementedWTesterServer() {}
func (UnimplementedWTesterServer) testEmbeddedByValue()                 {}

// UnsafeWTesterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WTesterServer will
// result in compilation errors.
type UnsafeWTesterServer interface {
	mustEmbedUnimplementedWTesterServer()
}

func RegisterWTesterServer(s grpc.ServiceRegistrar, srv WTesterServer) {
	// If the following call panics, it indicates UnimplementedWTesterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WTester_ServiceDesc, srv)
}

func _WTester_ActorRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WTesterServer).ActorRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WTester_ActorRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WTesterServer).ActorRegister(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WTester_ActorStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WTesterServer).ActorStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WTester_ActorStage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WTesterServer).ActorStage(ctx, req.(*StageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WTester_DirectorStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WTesterServer).DirectorStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WTester_DirectorStage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WTesterServer).DirectorStage(ctx, req.(*StageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WTester_ActorTerminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WTesterServer).ActorTerminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WTester_ActorTerminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WTesterServer).ActorTerminate(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WTester_ServiceDesc is the grpc.ServiceDesc for WTester service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WTester_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WTester",
	HandlerType: (*WTesterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActorRegister",
			Handler:    _WTester_ActorRegister_Handler,
		},
		{
			MethodName: "ActorStage",
			Handler:    _WTester_ActorStage_Handler,
		},
		{
			MethodName: "DirectorStage",
			Handler:    _WTester_DirectorStage_Handler,
		},
		{
			MethodName: "ActorTerminate",
			Handler:    _WTester_ActorTerminate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swarm.proto",
}
