// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swarm.proto

package swarm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatementKind int32

const (
	StatementKind_Register           StatementKind = 0 // 客户端注册
	StatementKind_UpdateState        StatementKind = 1 // 通知客户端执行阶段状态
	StatementKind_StartCoroutine     StatementKind = 3
	StatementKind_Loop               StatementKind = 4
	StatementKind_FbCoroutinesNumber StatementKind = 5 // 反馈当前并发个数
)

// Enum value maps for StatementKind.
var (
	StatementKind_name = map[int32]string{
		0: "Register",
		1: "UpdateState",
		3: "StartCoroutine",
		4: "Loop",
		5: "FbCoroutinesNumber",
	}
	StatementKind_value = map[string]int32{
		"Register":           0,
		"UpdateState":        1,
		"StartCoroutine":     3,
		"Loop":               4,
		"FbCoroutinesNumber": 5,
	}
)

func (x StatementKind) Enum() *StatementKind {
	p := new(StatementKind)
	*p = x
	return p
}

func (x StatementKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatementKind) Descriptor() protoreflect.EnumDescriptor {
	return file_swarm_proto_enumTypes[0].Descriptor()
}

func (StatementKind) Type() protoreflect.EnumType {
	return &file_swarm_proto_enumTypes[0]
}

func (x StatementKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatementKind.Descriptor instead.
func (StatementKind) EnumDescriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{0}
}

type ActorStatus int32

const (
	ActorStatus_WaitingOnline ActorStatus = 0 // 未上线
	ActorStatus_Online        ActorStatus = 1 // 在线
	ActorStatus_Offline       ActorStatus = 2 // 下线
	ActorStatus_Abnormal      ActorStatus = 3 // 异常掉线
)

// Enum value maps for ActorStatus.
var (
	ActorStatus_name = map[int32]string{
		0: "WaitingOnline",
		1: "Online",
		2: "Offline",
		3: "Abnormal",
	}
	ActorStatus_value = map[string]int32{
		"WaitingOnline": 0,
		"Online":        1,
		"Offline":       2,
		"Abnormal":      3,
	}
)

func (x ActorStatus) Enum() *ActorStatus {
	p := new(ActorStatus)
	*p = x
	return p
}

func (x ActorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_swarm_proto_enumTypes[1].Descriptor()
}

func (ActorStatus) Type() protoreflect.EnumType {
	return &file_swarm_proto_enumTypes[1]
}

func (x ActorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorStatus.Descriptor instead.
func (ActorStatus) EnumDescriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{1}
}

type StageKind int32

const (
	StageKind_StartStage  StageKind = 0 // 新阶段开始执行
	StageKind_FinishStage StageKind = 1 // 本阶段执行结束
)

// Enum value maps for StageKind.
var (
	StageKind_name = map[int32]string{
		0: "StartStage",
		1: "FinishStage",
	}
	StageKind_value = map[string]int32{
		"StartStage":  0,
		"FinishStage": 1,
	}
)

func (x StageKind) Enum() *StageKind {
	p := new(StageKind)
	*p = x
	return p
}

func (x StageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_swarm_proto_enumTypes[2].Descriptor()
}

func (StageKind) Type() protoreflect.EnumType {
	return &file_swarm_proto_enumTypes[2]
}

func (x StageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageKind.Descriptor instead.
func (StageKind) EnumDescriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{2}
}

type Status int32

const (
	Status_Success Status = 0
	Status_Fail    Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Success",
		1: "Fail",
	}
	Status_value = map[string]int32{
		"Success": 0,
		"Fail":    1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_swarm_proto_enumTypes[3].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_swarm_proto_enumTypes[3]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ActorStatus            `protobuf:"varint,1,opt,name=kind,proto3,enum=ActorStatus" json:"kind,omitempty"` // 请求类型：注册、掉线
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`                     // 子节点pod名称
	Host          *string                `protobuf:"bytes,3,opt,name=host,proto3,oneof" json:"host,omitempty"`             // 子节点连接串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetKind() ActorStatus {
	if x != nil {
		return x.Kind
	}
	return ActorStatus_WaitingOnline
}

func (x *RegisterRequest) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *RegisterRequest) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"` // 请求类型：注册、掉线
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *CommonResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Success
}

type StageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             StatementKind          `protobuf:"varint,1,opt,name=kind,proto3,enum=StatementKind" json:"kind,omitempty"`             // 请求类型：注册、掉线
	Pod              string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`                                   // 子节点pod名称
	StageIndex       uint32                 `protobuf:"varint,3,opt,name=StageIndex,proto3" json:"StageIndex,omitempty"`                    // 当前执行阶段
	CoroutinesNumber *uint32                `protobuf:"varint,4,opt,name=coroutinesNumber,proto3,oneof" json:"coroutinesNumber,omitempty"`  // 启动线程的个数
	Loop             *uint32                `protobuf:"varint,5,opt,name=loop,proto3,oneof" json:"loop,omitempty"`                          // 执行的个数
	StageKind        *StageKind             `protobuf:"varint,6,opt,name=stageKind,proto3,enum=StageKind,oneof" json:"stageKind,omitempty"` // 阶段消息类型
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StageRequest) Reset() {
	*x = StageRequest{}
	mi := &file_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageRequest) ProtoMessage() {}

func (x *StageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageRequest.ProtoReflect.Descriptor instead.
func (*StageRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *StageRequest) GetKind() StatementKind {
	if x != nil {
		return x.Kind
	}
	return StatementKind_Register
}

func (x *StageRequest) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *StageRequest) GetStageIndex() uint32 {
	if x != nil {
		return x.StageIndex
	}
	return 0
}

func (x *StageRequest) GetCoroutinesNumber() uint32 {
	if x != nil && x.CoroutinesNumber != nil {
		return *x.CoroutinesNumber
	}
	return 0
}

func (x *StageRequest) GetLoop() uint32 {
	if x != nil && x.Loop != nil {
		return *x.Loop
	}
	return 0
}

func (x *StageRequest) GetStageKind() StageKind {
	if x != nil && x.StageKind != nil {
		return *x.StageKind
	}
	return StageKind_StartStage
}

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{3}
}

var File_swarm_proto protoreflect.FileDescriptor

const file_swarm_proto_rawDesc = "" +
	"\n" +
	"\vswarm.proto\"g\n" +
	"\x0fRegisterRequest\x12 \n" +
	"\x04kind\x18\x01 \x01(\x0e2\f.ActorStatusR\x04kind\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x17\n" +
	"\x04host\x18\x03 \x01(\tH\x00R\x04host\x88\x01\x01B\a\n" +
	"\x05_host\"1\n" +
	"\x0eCommonResponse\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\x0e2\a.StatusR\x06status\"\x89\x02\n" +
	"\fStageRequest\x12\"\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x0e.StatementKindR\x04kind\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1e\n" +
	"\n" +
	"StageIndex\x18\x03 \x01(\rR\n" +
	"StageIndex\x12/\n" +
	"\x10coroutinesNumber\x18\x04 \x01(\rH\x00R\x10coroutinesNumber\x88\x01\x01\x12\x17\n" +
	"\x04loop\x18\x05 \x01(\rH\x01R\x04loop\x88\x01\x01\x12-\n" +
	"\tstageKind\x18\x06 \x01(\x0e2\n" +
	".StageKindH\x02R\tstageKind\x88\x01\x01B\x13\n" +
	"\x11_coroutinesNumberB\a\n" +
	"\x05_loopB\f\n" +
	"\n" +
	"_stageKind\"\x12\n" +
	"\x10TerminateRequest*d\n" +
	"\rStatementKind\x12\f\n" +
	"\bRegister\x10\x00\x12\x0f\n" +
	"\vUpdateState\x10\x01\x12\x12\n" +
	"\x0eStartCoroutine\x10\x03\x12\b\n" +
	"\x04Loop\x10\x04\x12\x16\n" +
	"\x12FbCoroutinesNumber\x10\x05*G\n" +
	"\vActorStatus\x12\x11\n" +
	"\rWaitingOnline\x10\x00\x12\n" +
	"\n" +
	"\x06Online\x10\x01\x12\v\n" +
	"\aOffline\x10\x02\x12\f\n" +
	"\bAbnormal\x10\x03*,\n" +
	"\tStageKind\x12\x0e\n" +
	"\n" +
	"StartStage\x10\x00\x12\x0f\n" +
	"\vFinishStage\x10\x01*\x1f\n" +
	"\x06Status\x12\v\n" +
	"\aSuccess\x10\x00\x12\b\n" +
	"\x04Fail\x10\x012\xda\x01\n" +
	"\aWTester\x124\n" +
	"\rActorRegister\x12\x10.RegisterRequest\x1a\x0f.CommonResponse\"\x00\x12.\n" +
	"\n" +
	"ActorStage\x12\r.StageRequest\x1a\x0f.CommonResponse\"\x00\x121\n" +
	"\rDirectorStage\x12\r.StageRequest\x1a\x0f.CommonResponse\"\x00\x126\n" +
	"\x0eActorTerminate\x12\x11.TerminateRequest\x1a\x0f.CommonResponse\"\x00B&Z$github.com/theforce/pkg/runner/swarmb\x06proto3"

var (
	file_swarm_proto_rawDescOnce sync.Once
	file_swarm_proto_rawDescData []byte
)

func file_swarm_proto_rawDescGZIP() []byte {
	file_swarm_proto_rawDescOnce.Do(func() {
		file_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)))
	})
	return file_swarm_proto_rawDescData
}

var file_swarm_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_swarm_proto_goTypes = []any{
	(StatementKind)(0),       // 0: StatementKind
	(ActorStatus)(0),         // 1: ActorStatus
	(StageKind)(0),           // 2: StageKind
	(Status)(0),              // 3: Status
	(*RegisterRequest)(nil),  // 4: RegisterRequest
	(*CommonResponse)(nil),   // 5: CommonResponse
	(*StageRequest)(nil),     // 6: StageRequest
	(*TerminateRequest)(nil), // 7: TerminateRequest
}
var file_swarm_proto_depIdxs = []int32{
	1, // 0: RegisterRequest.kind:type_name -> ActorStatus
	3, // 1: CommonResponse.status:type_name -> Status
	0, // 2: StageRequest.kind:type_name -> StatementKind
	2, // 3: StageRequest.stageKind:type_name -> StageKind
	4, // 4: WTester.ActorRegister:input_type -> RegisterRequest
	6, // 5: WTester.ActorStage:input_type -> StageRequest
	6, // 6: WTester.DirectorStage:input_type -> StageRequest
	7, // 7: WTester.ActorTerminate:input_type -> TerminateRequest
	5, // 8: WTester.ActorRegister:output_type -> CommonResponse
	5, // 9: WTester.ActorStage:output_type -> CommonResponse
	5, // 10: WTester.DirectorStage:output_type -> CommonResponse
	5, // 11: WTester.ActorTerminate:output_type -> CommonResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_swarm_proto_init() }
func file_swarm_proto_init() {
	if File_swarm_proto != nil {
		return
	}
	file_swarm_proto_msgTypes[0].OneofWrappers = []any{}
	file_swarm_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swarm_proto_goTypes,
		DependencyIndexes: file_swarm_proto_depIdxs,
		EnumInfos:         file_swarm_proto_enumTypes,
		MessageInfos:      file_swarm_proto_msgTypes,
	}.Build()
	File_swarm_proto = out.File
	file_swarm_proto_goTypes = nil
	file_swarm_proto_depIdxs = nil
}
