// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: helloworld.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C             int64                  `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	D             uint32                 `protobuf:"varint,4,opt,name=d,proto3" json:"d,omitempty"`
	E             uint64                 `protobuf:"varint,5,opt,name=e,proto3" json:"e,omitempty"`
	F             int32                  `protobuf:"zigzag32,6,opt,name=f,proto3" json:"f,omitempty"`
	G             int64                  `protobuf:"zigzag64,7,opt,name=g,proto3" json:"g,omitempty"`
	H             uint32                 `protobuf:"fixed32,8,opt,name=h,proto3" json:"h,omitempty"`
	I             uint64                 `protobuf:"fixed64,9,opt,name=i,proto3" json:"i,omitempty"`
	J             int32                  `protobuf:"fixed32,10,opt,name=j,proto3" json:"j,omitempty"`
	K             int64                  `protobuf:"fixed64,11,opt,name=k,proto3" json:"k,omitempty"`
	L             float32                `protobuf:"fixed32,12,opt,name=l,proto3" json:"l,omitempty"`
	M             float64                `protobuf:"fixed64,13,opt,name=m,proto3" json:"m,omitempty"`
	N             bool                   `protobuf:"varint,14,opt,name=n,proto3" json:"n,omitempty"`
	O             []byte                 `protobuf:"bytes,15,opt,name=o,proto3" json:"o,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *HelloRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *HelloRequest) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *HelloRequest) GetD() uint32 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *HelloRequest) GetE() uint64 {
	if x != nil {
		return x.E
	}
	return 0
}

func (x *HelloRequest) GetF() int32 {
	if x != nil {
		return x.F
	}
	return 0
}

func (x *HelloRequest) GetG() int64 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *HelloRequest) GetH() uint32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *HelloRequest) GetI() uint64 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *HelloRequest) GetJ() int32 {
	if x != nil {
		return x.J
	}
	return 0
}

func (x *HelloRequest) GetK() int64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *HelloRequest) GetL() float32 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *HelloRequest) GetM() float64 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *HelloRequest) GetN() bool {
	if x != nil {
		return x.N
	}
	return false
}

func (x *HelloRequest) GetO() []byte {
	if x != nil {
		return x.O
	}
	return nil
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_helloworld_proto protoreflect.FileDescriptor

const file_helloworld_proto_rawDesc = "" +
	"\n" +
	"\x10helloworld.proto\x12\n" +
	"helloworld\"\xe0\x01\n" +
	"\fHelloRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\x12\f\n" +
	"\x01c\x18\x03 \x01(\x03R\x01c\x12\f\n" +
	"\x01d\x18\x04 \x01(\rR\x01d\x12\f\n" +
	"\x01e\x18\x05 \x01(\x04R\x01e\x12\f\n" +
	"\x01f\x18\x06 \x01(\x11R\x01f\x12\f\n" +
	"\x01g\x18\a \x01(\x12R\x01g\x12\f\n" +
	"\x01h\x18\b \x01(\aR\x01h\x12\f\n" +
	"\x01i\x18\t \x01(\x06R\x01i\x12\f\n" +
	"\x01j\x18\n" +
	" \x01(\x0fR\x01j\x12\f\n" +
	"\x01k\x18\v \x01(\x10R\x01k\x12\f\n" +
	"\x01l\x18\f \x01(\x02R\x01l\x12\f\n" +
	"\x01m\x18\r \x01(\x01R\x01m\x12\f\n" +
	"\x01n\x18\x0e \x01(\bR\x01n\x12\f\n" +
	"\x01o\x18\x0f \x01(\fR\x01o\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2I\n" +
	"\aGreeter\x12>\n" +
	"\bSayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00B\x1fZ\x1dgithub.com/wtester/helloworldb\x06proto3"

var (
	file_helloworld_proto_rawDescOnce sync.Once
	file_helloworld_proto_rawDescData []byte
)

func file_helloworld_proto_rawDescGZIP() []byte {
	file_helloworld_proto_rawDescOnce.Do(func() {
		file_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_proto_rawDesc), len(file_helloworld_proto_rawDesc)))
	})
	return file_helloworld_proto_rawDescData
}

var file_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_helloworld_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: helloworld.HelloRequest
	(*HelloReply)(nil),   // 1: helloworld.HelloReply
}
var file_helloworld_proto_depIdxs = []int32{
	0, // 0: helloworld.Greeter.SayHello:input_type -> helloworld.HelloRequest
	1, // 1: helloworld.Greeter.SayHello:output_type -> helloworld.HelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_proto_init() }
func file_helloworld_proto_init() {
	if File_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_proto_rawDesc), len(file_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_proto_goTypes,
		DependencyIndexes: file_helloworld_proto_depIdxs,
		MessageInfos:      file_helloworld_proto_msgTypes,
	}.Build()
	File_helloworld_proto = out.File
	file_helloworld_proto_goTypes = nil
	file_helloworld_proto_depIdxs = nil
}
