- name: f_stage
  number_concurrent: 100
  sampling: 1
  ramp_up: 10
  duration: 10s
  execution_mode: random
  tasks:
    - type: grpc
      task:
        name: gg_task
        description: 登录
        url: localhost:50051
        service: Greeter
        method: SayHello
        params:
          - type: map
            param: { "name": "weicai" }